import type { XPost } from '../models/post.ts';
import type { ResearchReport } from '../models/report.ts';

function fmtNum(n: number | undefined): string {
  if (n === undefined) return '?';
  if (n < 1000) return String(n);
  if (n < 1_000_000) return `${(n / 1000).toFixed(1).replace(/\.0$/, '')}k`;
  return `${(n / 1_000_000).toFixed(1).replace(/\.0$/, '')}M`;
}

function postById(report: ResearchReport, id: string): XPost | undefined {
  if (report.thread.rootPost.id === id) return report.thread.rootPost;
  return (
    report.thread.authorPosts.find((p) => p.id === id) ??
    report.thread.quoteTweets.find((p) => p.id === id) ??
    report.thread.comments.find((p) => p.id === id)
  );
}

export function renderReportMarkdown(report: ResearchReport): string {
  const root = report.thread.rootPost;
  const m = root.metrics;
  const out: string[] = [];

  out.push(`# Thread Research — @${root.author.handle}`);
  if (report.topic) out.push(`> **Topic:** ${report.topic}`);
  out.push('');
  out.push(`**URL:** ${root.url}`);
  if (root.createdAt) out.push(`**Posted:** ${root.createdAt}`);
  out.push(
    `**Engagement:** ${fmtNum(m.likes)} likes · ${fmtNum(m.reposts)} reposts · ${fmtNum(m.replies)} replies · ${fmtNum(m.views)} views`,
  );
  out.push(
    `**Model:** \`${report.source.model}\` · cache: ${report.source.cacheHit ? 'hit' : 'miss'}`,
  );
  out.push('');

  if (report.warnings.length > 0) {
    out.push(`> ⚠ ${report.warnings.join(' · ')}`);
    out.push('');
  }

  out.push('## TL;DR');
  out.push(report.tldr);
  out.push('');

  out.push('## Summary');
  out.push(report.summary);
  out.push('');

  if (report.coverage || report.stanceDistribution) {
    out.push('## Conversation Analysis');
    if (report.coverage) {
      const cov = report.coverage;
      out.push(
        `**Coverage:** ${cov.fetchedReplies}/${cov.targetReplies} replies fetched · depth ${cov.achievedDepth}/${cov.targetDepth} · ${cov.classifiedReplies} classified · status ${cov.status}`,
      );
    }
    if (report.stanceDistribution) {
      const d = report.stanceDistribution;
      out.push(
        `**Stance distribution:** ${d.agree} agree · ${d.disagree} disagree · ${d.neutral} neutral · ${d.question} question · ${d.humor} humor · ${d.meta} meta`,
      );
    }
    out.push('');
  }

  if (report.keyInsights.length > 0) {
    out.push('## Key Insights');
    for (const k of report.keyInsights) {
      const tag = `[${k.confidence}]`;
      const evidence =
        k.evidencePostIds.length > 0
          ? ` _(evidence: ${k.evidencePostIds.map((id) => `\`${id}\``).join(', ')})_`
          : '';
      out.push(`- **${tag}** ${k.insight}${evidence}`);
    }
    out.push('');
  }

  if (report.notableReplies.length > 0) {
    out.push('## Notable Replies');
    for (const r of report.notableReplies) {
      const post = postById(report, r.postId);
      const who = post ? `@${post.author.handle}` : 'unknown';
      out.push(`- **${who}** — ${r.reason}`);
      if (r.summary) out.push(`  > ${r.summary}`);
      if (post) {
        const snippet = post.text.replace(/\s+/g, ' ').slice(0, 180);
        out.push(
          `  > _“${snippet}${post.text.length > 180 ? '…' : ''}”_  (♥${fmtNum(post.metrics.likes)})`,
        );
      }
    }
    out.push('');
  }

  if (report.openQuestions.length > 0) {
    out.push('## Open Questions');
    for (const q of report.openQuestions) out.push(`- ${q}`);
    out.push('');
  }

  out.push('## Source — Root Post');
  out.push('```');
  out.push(root.text);
  out.push('```');

  if (report.thread.authorPosts.length > 0) {
    out.push('');
    out.push('### Author follow-ups');
    for (const p of report.thread.authorPosts) {
      out.push(`- ${p.text.replace(/\n/g, ' ')}`);
    }
  }

  if (report.thread.quoteTweets.length > 0) {
    out.push('');
    out.push(`### Quote tweets (${report.thread.quoteTweets.length})`);
    for (const q of report.thread.quoteTweets.slice(0, 10)) {
      out.push(`- **@${q.author.handle}**: ${q.text.replace(/\n/g, ' ').slice(0, 240)}`);
    }
  }

  if (report.thread.comments.length > 0) {
    out.push('');
    out.push(`### Top replies (${report.thread.comments.length})`);
    for (const c of report.thread.comments.slice(0, 20)) {
      out.push(
        `- **@${c.author.handle}** (♥${fmtNum(c.metrics.likes)}): ${c.text.replace(/\n/g, ' ').slice(0, 240)}`,
      );
    }
  }

  out.push('');
  out.push('---');
  out.push(`_Generated by XRay at ${report.generatedAt}_`);

  return out.join('\n');
}
