/**
 * P4.2 — Markdown renderer for `ProfileReport`.
 *
 * Output structure (sections render only when non-empty):
 *
 *   # Profile — @handle
 *   **Sampling:** cache · **Threads:** N · **Comments:** M · **Cost:** $0.06
 *   ## Summary
 *   ...
 *   ## Top Topics
 *   table: Topic | Mentions | Confidence | Snippet
 *   ## Stance
 *   table: Subject | Stance | Evidence
 *   ## Expertise
 *   bullet list
 *   ## Notable Quotes
 *   blockquotes
 *   ---
 *   *Generated by XRay v0.5.0 at {generatedAt}*
 *
 * Warnings (when `partial: true`) render as a callout block above the
 * Summary so callers see degraded-output context up front.
 */
import type { ProfileReport } from '../models/profile.ts';

const XRAY_VERSION = '0.5.0';
const TABLE_SNIPPET_CHARS = 80;
const TABLE_EVIDENCE_CHARS = 60;

function fmtCost(cost: number): string {
  if (cost === 0) return '$0';
  if (cost < 0.01) return `$${cost.toFixed(4)}`;
  return `$${cost.toFixed(3)}`;
}

function tableCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function clamp(text: string, max: number): string {
  const collapsed = text.replace(/\s+/g, ' ').trim();
  if (collapsed.length <= max) return collapsed;
  return `${collapsed.slice(0, Math.max(0, max - 1))}…`;
}

export function renderProfileMarkdown(report: ProfileReport): string {
  const out: string[] = [];

  out.push(`# Profile — @${report.handle}`);
  out.push('');

  const meta = [
    `**Sampling:** ${report.samplingScope}`,
    `**Threads:** ${report.cachedThreadsAnalyzed}`,
    `**Comments:** ${report.cachedCommentsAnalyzed}`,
    `**Cost:** ${fmtCost(report.estimatedCostUsd)}`,
  ];
  out.push(meta.join(' · '));
  out.push('');

  if (report.partial && report.warnings.length > 0) {
    out.push(`> **Partial result.** ${report.warnings.join(' · ')}`);
    out.push('');
  }

  // ─── Summary ──────────────────────────────────────────────────────
  if (report.summary.trim()) {
    out.push('## Summary');
    out.push('');
    out.push(report.summary.trim());
    out.push('');
  }

  // ─── Top Topics ──────────────────────────────────────────────────
  if (report.topics.length > 0) {
    out.push('## Top Topics');
    out.push('');
    out.push('| Topic | Mentions | Confidence | Snippet |');
    out.push('|---|---:|---|---|');
    for (const t of report.topics) {
      const snippet = t.representativeSnippet
        ? tableCell(clamp(t.representativeSnippet, TABLE_SNIPPET_CHARS))
        : '—';
      out.push(`| ${tableCell(t.topic)} | ${t.mentions} | ${t.confidence} | ${snippet} |`);
    }
    out.push('');
  }

  // ─── Stance ───────────────────────────────────────────────────────
  if (report.stance.length > 0) {
    out.push('## Stance');
    out.push('');
    out.push('| Subject | Stance | Confidence | Evidence |');
    out.push('|---|---|---|---|');
    for (const s of report.stance) {
      const evidence = s.evidenceSnippets.length
        ? s.evidenceSnippets.map((e) => `"${tableCell(clamp(e, TABLE_EVIDENCE_CHARS))}"`).join(', ')
        : '—';
      out.push(`| ${tableCell(s.subject)} | ${s.stance} | ${s.confidence} | ${evidence} |`);
    }
    out.push('');
  }

  // ─── Expertise ────────────────────────────────────────────────────
  if (report.expertiseAreas.length > 0) {
    out.push('## Expertise');
    out.push('');
    for (const area of report.expertiseAreas) {
      out.push(`- ${area}`);
    }
    out.push('');
  }

  // ─── Notable Quotes ───────────────────────────────────────────────
  if (report.notableQuotes.length > 0) {
    out.push('## Notable Quotes');
    out.push('');
    for (const q of report.notableQuotes) {
      const quoteText = q.text.replace(/\n/g, '\n> ');
      let line = `> "${quoteText}"`;
      const attribution: string[] = [];
      if (q.context) attribution.push(q.context);
      if (q.sourceUrl) attribution.push(`[source](${q.sourceUrl})`);
      if (attribution.length > 0) line += ` — ${attribution.join(', ')}`;
      out.push(line);
      out.push('');
    }
  }

  // ─── Empty-cache fallback ────────────────────────────────────────
  // When all main sections are empty (e.g., Kyma failures across the
  // board) keep at least a footer so the output isn't a single line.
  if (
    !report.summary.trim() &&
    report.topics.length === 0 &&
    report.stance.length === 0 &&
    report.expertiseAreas.length === 0 &&
    report.notableQuotes.length === 0
  ) {
    out.push('_No synthesized content — all 3 Kyma calls failed. Check `warnings` above._');
    out.push('');
  }

  out.push('---');
  out.push(`*Generated by XRay v${XRAY_VERSION} at ${report.generatedAt}*`);

  return out.join('\n');
}
